name: LPRNet_TPS
base: ['config/ccpd_aug_base.yaml']
arch:
  preprocess:
    type: TPS
    args:
      F: 20
      I_size: [24, 94]
      I_r_size: [24, 94]
      I_channel_num: 3
      scale: 0.25
  algorithm: rec
  backbone:
    type: LPRNet
    args:
      dropout_rate: 0.5
  neck: {}
  head: {}
converter:
  type: CTCLabelConverter
  args:
    character: license_plate
metric:
  type: STRMeters
loss:
  type: CTCLoss
optimizer:
  type: Adadelta # Adam
  args:
    lr: 0.1
lr_scheduler:
  type: MultiStepLR
  args:
    milestones: [80, 120]
trainer:
  seed: 2
  epochs: 150
  log_iter: 100
  show_images_iter: 500
  resume_checkpoint: ''
  finetune_checkpoint: 'output/LPRNet_rec/checkpoint/model_best.pth'
  output_dir: output
  tensorboard: true
dataset:
  train:
    dataset:
      args:
        data_path:
          - /home/wjj/src/new_ccpd/CCPD2019/icdar_format/train.txt
        img_mode: RGB
    loader:
      batch_size: 32
      shuffle: true
      pin_memory: true
      num_workers: 8
      collate_fn:
        type: AlignCollate
        args:
          imgH: 24
          imgW: 94
          keep_ratio_with_pad: false
  validate:
    dataset:
      args:
        data_path:
          - /home/wjj/src/new_ccpd/CCPD2019/icdar_format/test.txt
        img_mode: RGB
    loader:
      batch_size: 32
      shuffle: true
      pin_memory: false
      num_workers: 8
      collate_fn:
        type: AlignCollate
        args:
          imgH: 24
          imgW: 94
          keep_ratio_with_pad: false

