name: LPRNet
base: ['config/ccpd_rec_test.yaml']
arch:
  algorithm: rec
  backbone:
    type: LPRNet
    args:
      dropout_rate: 0.5
  neck: {}
  head: {}
converter:
  type: CTCLabelConverter
  args:
    character: license_plate
post_processing:
  type: SegDetectorRepresenter
  args:
    thresh: 0.3
    box_thresh: 0.7
    max_candidates: 1000
    unclip_ratio: 3.0 # from paper
metric:
  type: STRMeters
loss:
  type: CTCLoss
optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
lr_scheduler:
  type: WarmupPolyLR
  args:
    warmup_epoch: 0.0001
trainer:
  seed: 2
  epochs: 200
  log_iter: 100
  show_images_iter: 500
  resume_checkpoint: ''
  finetune_checkpoint: ''
  output_dir: output
  tensorboard: true
dataset:
  train:
    dataset:
      args:
        data_path:
          - /home/wjj/src/new_ccpd/CCPD2019/icdar_format/train.txt
        img_mode: RGB
    loader:
      batch_size: 32
      shuffle: true
      pin_memory: true
      num_workers: 8
      collate_fn:
        type: AlignCollate
        args:
          imgH: 24
          imgW: 94
          keep_ratio_with_pad: false
  validate:
    dataset:
      args:
        data_path:
          - /home/wjj/src/new_ccpd/CCPD2019/icdar_format/test.txt
        img_mode: RGB
    loader:
      batch_size: 32
      shuffle: true
      pin_memory: false
      num_workers: 8
      collate_fn:
        type: AlignCollate
        args:
          imgH: 24
          imgW: 94
          keep_ratio_with_pad: false

